### ISSUE TITLE
Installation fails with download error

### ISSUE THREAD

**Issue by AuthenticPumpkin** [chuangzhu/standardnotes-milkdown#1]
In the Standard Notes web app, if I do "Import Extension" and then paste in the follow url:
https://sn-extensions.melty.land/milkdown/ext.json

this error text is presented:
"Error downloading package details. Please check the Extension Link and try again."

I have been able to install scratch editor just now, so my setup is working ok. For reference - it turns out that scratch editor had a similar issue a few weeks ago and were able to resolve it - https://github.com/dylanonelson/sn-scratch-editor/issues/27

**Comment by chuangzhu** [comment]
Thanks for the feedback. Seems like the a recent update of Standard Notes added a few request headers, causing my previous server-side CORS configuration breaks. Fixed server-side with the following changes:

```diff
-      add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
+      add_header 'Access-Control-Allow-Headers' '*';
```

**Comment by AuthenticPumpkin** [comment]
Thank you! It's fixed.

Thank you for all your work on this!
