### ISSUE TITLE
Syntax to denote Mermaid code

### ISSUE THREAD

**Issue by shompoe** [chuangzhu/standardnotes-milkdown#4]
Hello,

What syntax does the editor expect in order to denote the code for displaying a Mermaid chart?

**Comment by chuangzhu** [comment]
Check out https://mermaid-js.github.io/mermaid/#/

**Comment by shompoe** [comment]
Hi,

I did look at this and I tried copying some of the example code into the editor but it was just treating it like normal text. So I thought maybe I need to tell the editor somehow to expect mermaid code first?

--- 
Mark Desrousseaux



10 Feb 2022, 23:55 by ***@***.***:

**Comment by chuangzhu** [comment]
Enter ` ```mermaid ` and a space to create a mermaid block.
